management:
  server:
    port: 8080
logging:
  level:
    com.freelance.atelier_workshops: debug

spring:
  application:
    name: '@project.artifactId@'
    version: '@project.version@'
  datasource:
    url: jdbc:postgresql://localhost:5434/atelier
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        default_schema: atelier
        format_sql: true
    open-in-view: false

application:
  security:
    auth:
      username: admin
      password: admin123
    jwt:
      secretKey: mJt1fHl2U3VuSldOSHhCZ1R3U1BwOHJHRGpLdlA2SHE9PSQ2aXQ5QVpWUURwSUhp