management:
  server:
    port: 8080
logging:
  level:
    com.freelance.atelier_workshops: debug

spring:
  application:
    name: '@project.artifactId@'
    version: '@project.version@'
  datasource:
    url: jdbc:postgresql://${BBDD_HOST}:${BBDD_PORT}/${BBDD_NAME}
    username: ${BBDD_USER}
    password: ${BBDD_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        default_schema: atelier
        format_sql: true
    open-in-view: false

application:
  security:
    auth:
      username: ${AUTH_USERNAME}
      password: ${AUTH_PASSWORD}
    jwt:
      secretKey: ${SECRET_KEY}

# ENVIRONMENT VARIABLES
BBDD_HOST: localhost
BBDD_PORT: 5434
BBDD_NAME: atelier
BBDD_USER: admin
BBDD_PASSWORD: password